networks:
  backend:

services:
  mariadb:
    image: wodby/mariadb:latest
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    networks:
      - backend
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: mariadb
      PMA_VERBOSES: mariadb
      PMA_USER: $DB_ROOT_NAME
      PMA_PASSWORD: $DB_ROOT_PASSWORD
    networks:
      - backend
  php:
    image: wodby/php:8.1
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
    volumes:
      - ./:/var/www/html
    networks:
      - backend
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    ports:
      - 6379:6379
  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
      NGINX_VHOST_PRESET: ${NGINX_VHOST_PRESET}
    volumes:
      - ./:/var/www/
    ports:
      - 8000:80
    networks:
      - backend
