services:
  mariadb:
    image: wodby/mariadb:latest
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: mariadb
      PMA_VERBOSES: mariadb
      PMA_USER: $DB_ROOT_NAME
      PMA_PASSWORD: $DB_ROOT_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      UPLOAD_LIMIT: 1G
      PHP_MAX_INPUT_VARS: 1G

